export const VENUE_EXTRA_LABELS = {
	waiting: "待ち",
	labels: {
		overview: "全体像",
		prevDay: "前日",
		nationalFrame: "全国枠番",
		last10: "10走",
		commentsAndMotor: "コメント / モーター",
		displayInfo: "展示情報",
		before: "直前情報",
		start: "スタート展示",
		exhibition: "オリジナル展示",
		comments: "選手コメント",
		series: "今節成績",
		interval: "節間成績",
		recent: "最近成績",
		course: "進入コース別",
		motorStats: "モーター成績",
		motorEvaluation: "モーター評価",
		motorHistory: "モーター履歴",
		frameStats: "枠番別成績",
		framePast10: "枠番別10走",
		nationalRecent3: "全国過去3節",
		localRecent3: "当地過去3節",
		score: "得点率早見",
		entry: "選手成績",
		entryTable: "出走表",
		official: "公式直前",
		records: "成績・勝率",
		motor: "モーター",
		waterComment: "水面・コメント",
		diagnosis: "診断",
		exhibitionShort: "展示",
		startShort: "ST",
		scoreShort: "得点率",
		commentShort: "コメント",
		motorShort: "モーター",
		intervalShort: "節間",
		recentShort: "最近",
		entryShort: "成績",
		historyShort: "履歴",
		national3Short: "全国3",
		local3Short: "当地3",
		directBeforeShort: "直前",
		overviewShort: "全体",
		indexShort: "指数",
		nationalFrameShort: "全国枠番",
		last10Short: "10走",
		officialShort: "公式",
		recordsShort: "成績",
		motorHistoryShort: "機歴",
		waterShort: "水面",
	},
	hints: {
		overview: "大村公式データの収録状況",
		prevDay: "前日成績を確認",
		nationalFrame: "全国枠番別成績を確認",
		last10: "枠番別直近10走データ",
		commentsAndMotor: "選手コメントとモーター評価",
		displayInfo: "大村公式の展示情報を確認",
		beforeFull: "体重・調整・チルト・前走情報",
		beforeDisplay: "展示タイム・体重・チルト・前走情報",
		beforeWakamatsu: "体重・展示タイム・前走情報",
		startTsu: "津公式の ST とスタート順",
		startWakamatsu: "若松公式の ST とスタート順",
		startFukuoka: "福岡公式の ST とスタート順",
		startKojima: "児島公式の S/D・ST・スタート順",
		startBiwako: "びわこ公式の ST とスタート順",
		startGeneral: "公式 ST と進入・展示 ST を確認",
		exhibitionFull: "展示タイム・一周・回り足・直線",
		exhibitionDisplay: "展示タイム・一周・回り足・直線",
		commentsTsu: "選手コメントとモーターコメント",
		seriesGeneral: "今節の R・進入・ST・着順",
		recent: "最近の節間成績",
		courseCompare: "コース別の成績比較",
		courseWakamatsu: "進入コース別の 1着・2着・3着",
		motorStats: "モーター勝率と評価",
		motorEvaluation: "モーター成績と評価",
		motorHistory: "モーター成績と直近使用者",
		frameStats: "枠別の過去成績・平均 ST",
		framePast10: "枠別の過去10走・平均 ST",
		nationalRecent3: "全国での直近3節",
		localRecent3Tsu: "津での直近3節",
		localRecent3Wakamatsu: "若松での直近3節",
		scoreTsu: "津公式の得点率と勝率",
		scoreWakamatsu: "若松公式の得点率と勝率",
		scoreFukuoka: "福岡公式の得点率と勝率",
		scoreKojima: "児島公式の得点率と勝率",
		exhibitionBiwako: "びわこ公式の一周・まわり足・直線",
		seriesBiwako: "今節の R・進入・ST・着順",
		scoreBiwako: "びわこ公式の得点率と勝率",
		official: "展示タイムと公式の直前情報",
		records: "得点率早見から直前の成績差",
		exhibitionGeneral: "一周・回り足・直線比較",
		motorGeneral: "機歴やモーター評価を確認",
		waterComment: "潮汐や水面傾向・コメント",
		overviewTamagawa: "多摩川公式タブの全体像",
		motorTamagawa: "モーター履歴を確認",
		diagnosis: "能力指数を確認",
		interval: "節間成績を確認",
		beforeTamagawa: "体重・調整・前走情報",
		startTamagawa: "スタート展示を確認",
		exhibitionTamagawa: "オリジナル展示データ",
		framePast10Tamagawa: "枠別の直近10走",
		scoreTamagawa: "得点率早見",
		entryTable: "若松公式の出走表を表形式で表示",
		entryFukuoka: "勝率・ST・モーター成績",
	},
} as const;