import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const readJson = (relativePath) => JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8"));
const index = readJson("public/data/boatrace-ex/index.generated.json");
const output = readJson("public/data/boatrace-ex/derived/prediction-structure/latest.json");
const history = readJson(`public/data/boatrace-ex/history/races/${index.latestDate}.json`);
const ticketIndex = readJson("public/data/boatrace-ex/derived/prediction-structure/history-index.json");
const ticketHistorySummary = readJson("public/data/boatrace-ex/derived/prediction-structure/history-summary.json");
const latestTicketEntry = ticketIndex.dates.find((entry) => entry.date === index.latestDate);
const latestTickets = readJson(latestTicketEntry.path);
assert.equal(output.schemaVersion, "boat-ex-prediction-structure-v1");
assert.equal(output.targetDate, index.latestDate);
assert.equal(output.summary.raceCount, history.records.length);
assert.equal(output.summary.predictionTextAvailableRaceCount, latestTickets.summary.predictionTextAvailableRaceCount);
assert.equal(output.summary.structuredTicketAvailableRaceCount, latestTickets.summary.structuredTicketAvailableRaceCount);
assert.equal(output.summary.evaluatedPredictionRaceCount, latestTickets.summary.evaluatedPredictionRaceCount);
assert.equal(output.historyCoverage.historyRaceCount, ticketHistorySummary.historyRaceCount);
assert.equal(output.historyCoverage.predictionTextAvailableRaceCount, ticketHistorySummary.predictionTextAvailableRaceCount);
assert.ok(["ready", "partial", "insufficient-history", "unavailable"].includes(output.readiness.status));
assert.ok(output.sourceFiles.some((source) => source.sourcePath === "public/data/boatrace-ex/derived/prediction-structure/history-summary.json"));
console.log(JSON.stringify({ ok: true, targetDate: output.targetDate, latestSummary: output.summary, historyReadiness: output.readiness.status, historyCounts: { structuredTicketAvailableRaceCount: output.historyCoverage.structuredTicketAvailableRaceCount, evaluatedPredictionRaceCount: output.historyCoverage.evaluatedPredictionRaceCount } }, null, 2));
