import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const readJson = (relativePath) => JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8"));
const index = readJson("public/data/boatrace-ex/index.generated.json");
const output = readJson("public/data/boatrace-ex/derived/prediction-structure/latest.json");
const summary = readJson("public/data/boatrace-ex/derived/prediction-structure/history-summary.json");
const audit = readJson(`public/data/boatrace-ex/audit/prediction-structure-contract-${index.latestDate}.generated.json`);
const roughIndex = readJson("public/data/boatrace-ex/derived/rough-index/latest.json");
assert.equal(audit.kind, "boatrace-ex-prediction-structure-contract-audit");
assert.equal(audit.contract.parser, "strict-ticket-pattern after a buy-ticket marker and 3-trifecta group heading");
assert.equal(audit.contract.evaluation, "exact ordered boat-number triple only");
assert.equal(audit.targetDate.readiness.status, summary.readiness.status);
assert.equal(audit.historyCoverage.structuredTicketCount, summary.structuredTicketCount);
assert.equal(output.historyCoverage.structuredTicketCount, summary.structuredTicketCount);
assert.equal(summary.historyRaceCount, roughIndex.summary.raceCount);
assert.equal(summary.readiness.status, "insufficient-history");
console.log(JSON.stringify({ ok: true, targetDate: index.latestDate, historyRaceCount: summary.historyRaceCount, structuredTicketCount: summary.structuredTicketCount, evaluatedPredictionRaceCount: summary.evaluatedPredictionRaceCount, readiness: summary.readiness.status }, null, 2));
